# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R2_distances <- function(locA, locB) {
    .Call('_stmra_R2_distances', PACKAGE = 'stmra', locA, locB)
}

R3_distances <- function(locA, locB) {
    .Call('_stmra_R3_distances', PACKAGE = 'stmra', locA, locB)
}

S2_distances <- function(locA, locB) {
    .Call('_stmra_S2_distances', PACKAGE = 'stmra', locA, locB)
}

S2_distances_angular <- function(locA, locB) {
    .Call('_stmra_S2_distances_angular', PACKAGE = 'stmra', locA, locB)
}

R1_distances <- function(locA, locB) {
    .Call('_stmra_R1_distances', PACKAGE = 'stmra', locA, locB)
}

cov_nonstationary_latitude <- function(locA, locB, theta, n_knots = 9L) {
    .Call('_stmra_cov_nonstationary_latitude', PACKAGE = 'stmra', locA, locB, theta, n_knots)
}

